### ISSUE TITLE
Error rcon

### ISSUE THREAD

**Issue by LeonNRL** [conqp/rcon#9]
Hey,
Ich habe folgenden Code.
from rcon.source import Client
with Client('127.0.0.1', 30120, passwd='SECRET') as client:
    response = client.run(f"kill 2")

    print(response)
[Und bekomme folgenden Fehler: https://cdn.discordapp.com/attachments/922923546408288306/963156979503759440/unknown.png](https://cdn.discordapp.com/attachments/922923546408288306/963157368865194024/unknown.png)
was mache ich Falsch?

**Comment by conqp** [comment]
You did two things wrong
1) You did nor submit your bug report in English for everyone to understand.
2) You did not post an actual error message, bur merely a link to what may be an image.

I do not even bother to open and view the latter,  since it will not be archived with this bug repost for future reference. 
If you have an issue, please post the entire code producing it and the entire error message you get here for analysis and future reference.
Thank you.
